name: economy_app
description: "App para gestionar la economÃ­a familiar."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  web: ^1.1.1
  js: ^0.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
        - asset: assets/fonts/Montserrat-Bold.otf
